name: liten_app
description: 리튼(Liten) - 음성 듣기와 텍스트 쓰기를 통합한 크로스플랫폼 노트 앱

# 앱 버전 정보
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 상태 관리
  provider: ^6.1.1

  # 음성 녹음/재생
  audioplayers: ^5.2.1
  record: ^5.0.4

  # 파일 시스템
  path_provider: ^2.1.1
  path: ^1.8.3

  # 권한 관리
  permission_handler: ^11.0.1

  # 이미지 처리
  image_picker: ^1.0.4
  image: ^4.1.3

  # PDF/문서 처리
  pdf: ^3.10.4
  printing: ^5.11.0

  # HTTP 통신
  http: ^1.1.0
  dio: ^5.3.2

  # 로컬 저장소
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

  # UI 컴포넌트
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  # 유틸리티
  uuid: ^4.1.0
  intl: ^0.19.0
  url_launcher: ^6.2.1

  # 광고 (무료 버전)
  google_mobile_ads: ^4.0.0

  # 인앱 결제
  in_app_purchase: ^3.1.11

  # 파일 공유
  share_plus: ^7.2.1

  # 테마/UI
  flex_color_scheme: ^7.3.1
  flutter_colorpicker: ^1.0.3

  # 텍스트 에디터
  flutter_quill: ^8.6.4
  markdown: ^7.1.1

  # 필기 도구 (Canvas 기반)
  signature: ^5.4.0
  flutter_drawing_board: ^1.1.1
  
  # 수학 연산 (도형 계산용)
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Flutter 설정
flutter:
  uses-material-design: true

  # 앱 아이콘
  # assets:
  #   - images/
  #   - icons/

  # 다국어 지원
  generate: true

# 플랫폼별 설정
flutter:
  platforms:
    android:
      package: com.liten.app
    ios:
      bundle_identifier: com.liten.app
    web:
      theme_color: "#2196F3"
    windows:
      executable_name: liten_app
    macos:
      bundle_identifier: com.liten.app
    linux:
      executable_name: liten_app